name: workflow2
on:
 push:
  branches:
   - main
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: workflowJob1step1
     run: echo "Hello from push changes"
   - name: step2
     run: |
           echo "hello from step 2"
           sleep 30
           echo "hello from step2"
   - run: echo "Print hello without step name" 
