name: workflow1
on:
 pull_request:
  branches:
   - main
 schedule:
   - cron: "*/5 * * * *"
 workflow_dispatch:  
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: step1
     run: echo "Hello from push changes"
