name: workflow1
on:
 pull_request:
  branches:
   - main
 schedule:
   - cron: "*/5 * * * *"
 workflow_dispatch:  
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: step1
     run: echo "Hello from push changes"
   - name: step2
     run: |
           echo "hello from step 2"
           sleep 30
           echo "hello from step2"
   - run: echo "Print hello without step name" 
 job2:
  runs-on: ubuntu-latest
  steps:
   - name: stepJob2
     run: |
           echo "Hello from push changes"
           sleep 30
           echo "stepJob2"
   - name: stepJob3
     run: echo "Hello from push changes"
   
